[11:07 AM, 11/13/2024] +57 315 5545826: # This is a basic workflow to help you get started with Actions

name: Mi primera action

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  mybuild:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Runs a single command using the runners shell…
[11:27 AM, 11/13/2024] +57 315 5545826: Hacer fork del repositorio: https://github.com/CapitanFantastico/flask-hello-world
[11:28 AM, 11/13/2024] +57 315 5545826: Crear una cuenta en render.com
[11:30 AM, 11/13/2024] +57 315 5545826: Para crear la cuenta en Render, se autentican con la cuenta de GitHub
[11:57 AM, 11/13/2024] +57 315 5545826: name: Workflow Clase DS2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clonando el repositorio
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Validando software instalado
      run: |
        pip freeze

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Tests
      run: |
        python -m unittest discover -s tests
